@startuml

actor       ResourceOwner       as user
entity      Client              as client
entity      AuthorizationServer as idp
entity      ResourceServer      as api

user        -> client               : Requires data
client      -> idp                  : Redirects resource owner to authorization server to input his/her credentials
idp         -> idp                  : Resource owner inputs credentials
idp         -> client               : Authorization server redirect resource owner to the client with a code, for ex. 4981003201
client      -> idp                  : Sends a back-channel request with payload: Code + ClientId + ClientSecret
idp         -> client               : Token
client      -> api                  : Client uses token to access resouces on behalf of the resource owner
api         -> client               : Return data
client      -> user                 : Return data

@enduml