@startuml

actor       ResourceOwner       as user
entity      Client              as client
entity      AuthorizationServer as idp
entity      ResourceServer      as api

user        -> client               : Requires data
client      -> idp                  : Redirects resource owner to authorization server to input his/her credentials with client_id
idp         -> idp                  : Resource owner inputs credentials
idp         -> client               : Authorization server redirect resource owner to the client with a token
client      -> api                  : Client uses token to access resouces on behalf of the resource owner
api         -> client               : Return data
client      -> user                 : Return data

@enduml