@startuml

entity      Client              as client
entity      AuthorizationServer as idp
entity      ResourceServer      as api

client      -> idp                  : Sends a back-channel request with payload ClientId + ClientSecret to get a access token
idp         -> client               : Access Token
client      -> api                  : Client uses access token to access resouces (on behalf of itself!)
api         -> client               : Return data

@enduml