@startuml

actor       ResourceOwner       as user
entity      Client              as client
entity      AuthorizationServer as idp
entity      ResourceServer      as api

user        -> client               : Input credentials
client      -> idp                  : Client request access token from the authorization token using resource owner's credentials
idp         -> client               : Returns access token
client      -> api                  : Client uses access token to access resouces on behalf of the resource owner
api         -> client               : Return data
client      -> user                 : Return data

@enduml